[[main]]
    identifier = "news"
    name = "NEWS"
    pageRef =  "/posts/"
    weight = 10
[[main]]
    identifier = "competitions"
    name = "COMPETITION"
    pageRef = "/competitions/"
    weight = 20
[[main]]
    parent = "competitions"
    indentifier = "bulletins"
    name = "BULLETINS"
    pageRef = "/competitions/bulletins"
    weight = 21
[[main]]
    parent = "competitions"
    indentifier = "startlists"
    name = "START LIST"
    pageRef = "/competitions/startlists"
    weight = 22
[[main]]
    parent = "competitions"
    indentifier = "results"
    name = "RESULTS"
    pageRef = "/competitions/results"
    weight = 23
[[main]]
    identifier = "race_days"
    name = "RACE DAYS"
    pageRef = "/race_days/"
    weight = 30
[[main]]
    indentifier = "PHOTO"
    name = "PHOTO"
    weight = 50
[[main]]
    parent = "PHOTO"
    indentifier="preevent_day1"
    name = "Pre event day 1"
    url = "https://photos.app.goo.gl/j5LMnWZgFKxrxqY69"
    weight = 51
[[main]]
    parent = "PHOTO"
    indentifier="preevent_day2"
    name = "Pre event day 2"
    url = "https://photos.app.goo.gl/d9z6y3KYyaJGhyA29"
    weight = 52